<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Logout' => 'Вихід',
    'Url' => '',
    'Admin' => 'Адмін',
    'Administrator' => 'Адміністратор',
    'Client navbar' => 'Клієнтське меню',
    'Content' => 'Контент',
    'Delete' => 'Видалити',
    'Demo' => 'Демо',
    'Description' => 'Опис',
    'Disabled' => 'Виключено',
    'Email' => 'Ел. адрес',
    'Enabled' => 'Включено',
    'Home' => 'Головна',
    'Level' => 'Рівень',
    'Login' => 'Вхід',
    'Menu' => 'Меню',
    'No parent' => '-корінь-',
    'No relate' => 'Нема відношення',
    'Order' => 'Порядок',
    'Parent' => 'Корінь',
    'Password' => 'Пароль',
    'Please fill out the following fields to login' => 'Заповніть наступні поля для входу',
    'Relate menu category' => 'Відноситься до категорії меню',
    'Relate menu list' => 'Відносити до списку меню',
    'Relate menu unique' => 'Відносити до конктетного меню',
    'Remember me' => 'Запам\'ятати мене',
    'Role' => 'Роль',
    'Submenu' => 'Підменю',
    'Test type' => 'Тестовий тип',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Unknown menu enabled status' => 'Невідомий статус чи включений меню',
    'Unknown menu level' => 'Невідомий рівень меню',
    'Unknown menu type' => 'Невідомий тип меню',
    'Unknown role' => 'Невідома роль',
    'User' => 'Користувач',
    'Username' => 'Ім\'я користувача',
];
