<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cannot use related type without relate' => '',
    'Not need child parent convertion' => '',
    'Not need child type conversion' => '',
    'Responsive (max width 100%)' => 'Чутливий "responsive" (максимальна ширина 100%)',
    'Root cannot have parent' => '',
    'All menu levels' => 'Всі рівні меню',
    'All menu types' => 'Всі типи меню',
    'Article not found' => 'Стаття не знайдена',
    'Articles' => 'Статті',
    'Cannot find user to edit' => 'Не знайдено користувача для редагування',
    'Change password' => 'Змінити пароль',
    'Child parent conversion' => 'Конвертувати корінь',
    'Child type conversion' => 'Ковертувати тип',
    'Client area' => 'Клієнтська частина',
    'Company Name' => 'Назва компанії',
    'Company name would be display at some places' => 'Назва компанії буде використовуватись в деяких місцях сайту',
    'Convert childs to roots' => 'Конвертувати дочірні елементи в корені',
    'Create' => 'Створити',
    'Download' => 'Скачати',
    'Edit' => 'Редагувати',
    'Image File' => 'Картинка',
    'Image not found' => 'Картинка не знайдена',
    'Images' => 'Картинки',
    'Is site under maintance, checked mean to disable user interract with site (except users with administator role)' => 'Чи сайт на технічному обслуговуванні, активно - означає недоступність сайту для користувачів (окрім користувачів з роллю адміністратор)',
    'Maintance' => 'Технічне обслуговування',
    'Menu level' => 'Рівень меню',
    'Menu not found' => 'Меню не знайдено',
    'Menu type' => 'Тип меню',
    'Menus' => 'Меню',
    'Move childs to same root' => 'Перемістити дочірні елеметни в той же корінь',
    'Not change childs type' => 'Не змінювати тип дочірніх елементів',
    'Password' => 'Пароль',
    'Password mismatch' => 'Пароль неспівпадає',
    'Password repeat' => 'Повторіть пароль',
    'Relate with' => 'Зв\'язати з',
    'Related type' => 'Тип відношення',
    'Remove childs' => 'Видалити дочірні елементи',
    'Save' => 'Зберегти',
    'Settings' => 'Настройки',
    'Update childs type' => 'Обновити тип дочірніх елементів',
    'Upload' => 'Завантажити',
    'User not found' => 'Користувача не знайдено',
    'Users' => 'Користувачі',
];
